version: "3"
services:
  ccmc:
    image: ghcr.io/ej-aoat/crosscrown/crosscrown-mc:2.0-mc1.20.2
    build:
      context: ../../../
      dockerfile: ./app/SpigotMC/Docker/Dockerfile
    ports:
      - "25565:25565"
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ccmc-data:/opt/ccmc
volumes:
  ccmc-data:
    driver: local
