version: "3"
services:
  ccmc:
    image: 127.0.0.1:5000/crosscrown-mc:1.2-mc1.19.2
    tty: true
    build:
      context: ../../../
      dockerfile: ./app/SpigotMC/Docker/Dockerfile
    ports:
      - "25565:25565"
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ccmc-data:/opt/ccmc
volumes:
  ccmc-data:
    driver: local